Build on macOS Big Sur
GENIVI/dlt-viewer pull request #151
Opened 2020-12-02 05:47 UTC by hannesa2

2020-12-02 06:48 UTC, hannesa2 commented
This Travis is _super slow_, I build myself with Github action https://github.com/hannesa2/dlt-viewer/pull/1

If you are interested I can help you to move from Travis to Github action for all build variant

2020-12-17 10:43 UTC, alexmucde commented
Yes it would be great to get this improved. Best we would have builds for Windows/Linux/MacOs to be automatically verified.

2020-12-17 10:43 UTC, alexmucde requested changes
Signed off statement missing

2020-12-17 11:13 UTC, hannesa2 commented
Signed off is done

2020-12-17 14:42 UTC, alexmucde approved these changes

2020-12-17 14:42 UTC, merged